services:
  ui:
    build: ./ui
    security_opt:
          - apparmor:unconfined
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    # This command is for development, for production you might want to use the Nginx CMD from the Dockerfile
    command: npm start

  api:
    build: ./api
    security_opt:
          - apparmor:unconfined
    ports:
      - "8001:8001"
    volumes:
      - ./api:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uv run fastapi dev app/main.py --host 0.0.0.0 --port 8001
