services:
  user-ui:
    build:
      context: ./user-ui
      dockerfile: Dockerfile.dev
    security_opt:
      - apparmor:unconfined

    ports:
      - "5173:5173"

    develop:
      watch:
        - action: sync
          path: ./user-ui/src
          target: /app/src

        - action: sync
          path: ./user-ui/public
          target: /app/public

        - action: rebuild
          path: ./user-ui/package.json

    environment:
      - CHOKIDAR_USEPOLLING=true      # needed for hot-reload on some OS (Windows/WSL)
      - WATCHPACK_POLLING=true        # needed for Webpack 5 / CRA
    stdin_open: true                  # keeps process alive (needed for CRA)


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    security_opt:
      - apparmor:unconfined
    ports:
      - "8001:8001"

    volumes:
      - ./backend/logs:/app/logs  # TODO: why, what about watch ?

    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - __pycache__/
        - action: rebuild
          path: ./backend/pyproject.toml


    environment:
      - ENV=development
      - DATABASE_URL=sqlite:////app/app/test.db
    command: uv run fastapi dev app/main.py --host 0.0.0.0 --port 8001
    stdin_open: true


  prometheus:
    image: prom/prometheus:latest
    security_opt:
      - apparmor:unconfined  # this is to avoid This is a classic issue on Linux machines (especially Ubuntu). It is almost always caused by a conflict between AppArmor (the Linux kernel security module) and the Snap-installed version of Docker. error permission denied when trying to stop the container
    ports:
      - "9090:9090"
    volumes:
      - ./backend/prometheus.yml:/etc/prometheus/prometheus.yml:ro  # TODO: why not whatch ?
    depends_on:
      - backend


  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    security_opt:
      - apparmor:unconfined

volumes:
  grafana-data: