services:
  user-ui:
    build:
      context: ./user-ui
      dockerfile: Dockerfile.dev
    security_opt:
      - apparmor:unconfined

    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true      # needed for hot-reload on some OS (Windows/WSL)
    stdin_open: true                  # keeps process alive (needed for CRA)

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    security_opt:
      - apparmor:unconfined
    ports:
      - "8001:8001"
    environment:
      - ENV=development
    command: uv run fastapi dev app/main.py --host 0.0.0.0 --port 8001
